version: '3.8'
services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - UVICORN_WORKERS=1
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
